// dsh-ccswitch-plugin — derivative of 2995288295/dsh-ccswitch-importer-plus
// (Apache-2.0), which is itself a derivative of wtiaw/dsh-ccswitch-importer.
// Reworked for DSH 0.2.0-rc.2. See NOTICE for the full attribution chain.
/**
 * A small catalogue of provider presets, so "add a provider" does not begin
 * with an empty form and an endpoint the user has to look up.
 *
 * Every `baseURL` and model id below is transcribed from CC Switch 4.0.4's own
 * preset sources (`src/config/{claude,codex}ProviderPresets.ts`), not invented.
 * That matters more than it looks: a relay's endpoint is frequently NOT the
 * one its marketing site suggests — several providers serve Anthropic's
 * protocol from an `/anthropic` sub-path and OpenAI's from `/v1` on the same
 * host, and a preset that guesses gets a 404 that reads like a bad key.
 *
 * A preset is only a starting point. It fills the form; the user edits and
 * saves, and what gets stored is their provider, not this entry.
 *
 * Scope: only providers whose endpoint speaks one of the three protocols
 * `dsh-llm-pi-ai` can serve are listed. Anything CC Switch reaches over
 * Gemini's native protocol is deliberately absent — see `lib/core/extract.js`
 * for why importing one would produce a provider that can never answer.
 */

/**
 * @typedef {object} CCSProviderPreset
 * @property {string} key - stable id, unique within this list
 * @property {string} displayName - what the picker shows
 * @property {string} appType - the CC Switch app this was transcribed for
 * @property {string} api - one of {@link CCS_API_PROTOCOLS}
 * @property {string} baseURL - the endpoint's base, as CC Switch writes it
 * @property {string[]} models - model ids that endpoint serves
 * @property {string} [family] - the vendor this shares with its other versions
 * @property {string} [planKey] - the plan, when this vendor sells several
 * @property {string} [regionKey] - the region, when this vendor serves two
 * @property {string} [category] - one of {@link CCS_PROVIDER_CATEGORIES}
 * @property {boolean} [isPartner] - CC Switch marks this vendor a partner
 * @property {string} [icon] - CC Switch's icon name, for the picker
 * @property {string} [iconColor] - CC Switch's hex accent for that icon
 */

/** @type {readonly CCSProviderPreset[]} */
export const PROVIDER_PRESETS = Object.freeze([
  {
    key: "deepseek-claude",
    displayName: "DeepSeek",
    appType: "claude",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.deepseek.com/anthropic",
    models: ["deepseek-flash", "deepseek-v4-pro"],
    icon: "deepseek",
    iconColor: "#1E88E5",
  },
  {
    key: "kimi-claude",
    displayName: "Kimi",
    appType: "claude",
    family: "kimi",
    planKey: "payg",
    regionKey: "cn",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.moonshot.cn/anthropic",
    models: ["kimi-k2.7-code"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "kimi-codex",
    displayName: "Kimi (Codex)",
    appType: "codex",
    family: "kimi",
    planKey: "payg",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.moonshot.cn/v1",
    models: ["kimi-k3"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "zhipu-glm-claude",
    displayName: "Zhipu GLM",
    appType: "claude",
    family: "zhipu",
    regionKey: "cn",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://open.bigmodel.cn/api/anthropic",
    models: ["glm-5.3"],
    icon: "zhipu",
    iconColor: "#0F62FE",
  },
  {
    key: "zhipu-glm-codex",
    displayName: "Zhipu GLM (Codex)",
    appType: "codex",
    family: "zhipu",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://open.bigmodel.cn/api/v1",
    models: ["glm-5.3"],
    icon: "zhipu",
    iconColor: "#0F62FE",
  },
  {
    key: "siliconflow-claude",
    displayName: "SiliconFlow",
    appType: "claude",
    family: "siliconflow",
    regionKey: "cn",
    category: "aggregator",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://api.siliconflow.cn",
    models: ["Pro/MiniMaxAI/MiniMax-M2.5"],
    icon: "siliconflow",
    iconColor: "#6E29F6",
  },
  {
    key: "siliconflow-codex",
    displayName: "SiliconFlow (Codex)",
    appType: "codex",
    family: "siliconflow",
    regionKey: "cn",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.siliconflow.cn/v1",
    models: ["deepseek-ai/DeepSeek-V4-Flash"],
    icon: "siliconflow",
    iconColor: "#6E29F6",
  },
  {
    key: "modelscope-claude",
    displayName: "ModelScope",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://api-inference.modelscope.cn",
    models: ["ZhipuAI/GLM-5.2"],
    icon: "modelscope",
    iconColor: "#624AFF",
  },
  {
    key: "modelscope-codex",
    displayName: "ModelScope (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api-inference.modelscope.cn/v1",
    models: ["ZhipuAI/GLM-5.2"],
    icon: "modelscope",
    iconColor: "#624AFF",
  },
  {
    key: "minimax-claude",
    displayName: "MiniMax",
    appType: "claude",
    family: "minimax",
    regionKey: "cn",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.minimax.cn/anthropic",
    models: ["MiniMax-M3"],
    icon: "minimax",
    iconColor: "#FF6B6B",
  },
  {
    key: "minimax-codex",
    displayName: "MiniMax (Codex)",
    appType: "codex",
    family: "minimax",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.minimax.cn/v1",
    models: ["MiniMax-M3"],
    icon: "minimax",
    iconColor: "#FF6B6B",
  },
  {
    key: "openrouter-claude",
    displayName: "OpenRouter",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://openrouter.ai/api",
    models: ["anthropic/claude-haiku-4.5", "anthropic/claude-opus-5", "anthropic/claude-sonnet-5"],
    icon: "openrouter",
    iconColor: "#6566F1",
  },
  {
    key: "nvidia-claude",
    displayName: "Nvidia",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://integrate.api.nvidia.com",
    models: ["moonshotai/kimi-k3"],
    icon: "nvidia",
    iconColor: "#000000",
  },
  {
    key: "nvidia-codex",
    displayName: "Nvidia (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://integrate.api.nvidia.com/v1",
    models: ["moonshotai/kimi-k3"],
    icon: "nvidia",
    iconColor: "#000000",
  },
  {
    key: "xiaomi-mimo-claude",
    displayName: "Xiaomi MiMo",
    appType: "claude",
    family: "xiaomi-mimo",
    planKey: "payg",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.xiaomimimo.com/anthropic",
    models: ["mimo-v2.6-pro"],
    icon: "xiaomimimo",
    iconColor: "#000000",
  },
  {
    key: "xiaomi-mimo-codex",
    displayName: "Xiaomi MiMo (Codex)",
    appType: "codex",
    family: "xiaomi-mimo",
    planKey: "payg",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.xiaomimimo.com/v1",
    models: ["mimo-v2.6-pro"],
    icon: "xiaomimimo",
    iconColor: "#000000",
  },
  {
    key: "longcat-claude",
    displayName: "Longcat",
    appType: "claude",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.longcat.chat/anthropic",
    models: ["LongCat-2.0"],
    icon: "longcat",
    iconColor: "#29E154",
  },
  {
    key: "longcat-codex",
    displayName: "Longcat (Codex)",
    appType: "codex",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.longcat.chat/openai/v1",
    models: ["LongCat-2.0"],
    icon: "longcat",
    iconColor: "#29E154",
  },
  {
    key: "packycode-codex",
    displayName: "PackyCode (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://www.packyapi.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "packycode",
  },
  {
    key: "aihubmix-codex",
    displayName: "AiHubMix (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://aihubmix.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "aihubmix",
    iconColor: "#006FFB",
  },
  {
    key: "ppio-claude",
    displayName: "PPIO",
    appType: "claude",
    category: "aggregator",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://api.ppio.com/anthropic",
    models: ["deepseek/deepseek-v4-flash-0731"],
    icon: "ppio",
    iconColor: "#2874FF",
  },
  {
    key: "ppio-codex",
    displayName: "PPIO (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.ppio.com/openai/v1",
    models: ["deepseek/deepseek-v4-flash-0731"],
    icon: "ppio",
    iconColor: "#2874FF",
  },
  {
    key: "stepfun-claude",
    displayName: "StepFun",
    appType: "claude",
    family: "stepfun",
    regionKey: "cn",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.stepfun.com/step_plan",
    models: ["step-3.5-flash-2603"],
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  {
    key: "stepfun-codex",
    displayName: "StepFun (Codex)",
    appType: "codex",
    family: "stepfun",
    planKey: "stepPlan",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.stepfun.com/step_plan/v1",
    models: ["step-3.7-flash"],
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  {
    key: "bailing-claude",
    displayName: "BaiLing",
    appType: "claude",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.ant-ling.com/anthropic",
    models: ["Ling-2.6-1T"],
    icon: "bailing",
  },
  {
    key: "bailing-codex",
    displayName: "BaiLing (Codex)",
    appType: "codex",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.ant-ling.com/v1",
    models: ["Ling-2.6-1T"],
    icon: "bailing",
  },
  {
    key: "volcengine-doubao-claude",
    displayName: "Volcengine Doubao",
    appType: "claude",
    family: "volcengine",
    planKey: "payg",
    category: "cn_official",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://ark.cn-beijing.volces.com/api/compatible",
    models: ["doubao-seed-2-1-pro-260628"],
    icon: "doubao",
    iconColor: "#3370FF",
  },
  {
    key: "volcengine-doubao-codex",
    displayName: "Volcengine Doubao (Codex)",
    appType: "codex",
    family: "volcengine",
    planKey: "payg",
    category: "cn_official",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    models: ["doubao-seed-2-1-pro-260628"],
    icon: "doubao",
    iconColor: "#3370FF",
  },

  // --- transcribed from CC Switch 4.0.6 (claude, 35 entries) ---
  //
  // Generated from `src/config/claudeProviderPresets.ts` by bundling that
  // module and reading the evaluated presets, so these endpoints are the ones
  // CC Switch itself writes rather than the ones its marketing pages suggest.
  // The hand-written block above is kept as-is; anything whose endpoint it
  // already ships is not repeated here.
  //
  // Excluded: entries with no model id (llm-pi-ai rejects an empty model list),
  // OAuth-only entries (DSH has no sign-in path), and endpoint templates like
  // `bedrock-runtime.${AWS_REGION}...` that parse as URLs but cannot be dialled.
  {
    key: "kimi-global-claude",
    displayName: "Kimi Global",
    appType: "claude",
    family: "kimi",
    planKey: "payg",
    regionKey: "intl",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.moonshot.ai/anthropic",
    models: ["kimi-k2.7-code"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "kimi-for-coding-claude",
    displayName: "Kimi For Coding",
    appType: "claude",
    family: "kimi",
    planKey: "coding",
    regionKey: "cn",
    category: "cn_official",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://api.kimi.com/coding/",
    models: ["kimi-for-coding"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "kimi-for-coding-global-claude",
    displayName: "Kimi For Coding Global",
    appType: "claude",
    family: "kimi",
    planKey: "coding",
    regionKey: "intl",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.kimi.ai/coding/",
    models: ["kimi-for-coding"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "shengsuanyun-claude",
    displayName: "Shengsuanyun",
    appType: "claude",
    category: "aggregator",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://router.shengsuanyun.com/api",
    models: ["anthropic/claude-sonnet-5", "anthropic/claude-opus-5", "anthropic/claude-haiku-4.5"],
    icon: "shengsuanyun",
  },
  {
    key: "fluxa-token-plan-claude",
    displayName: "FluxA Token Plan",
    appType: "claude",
    category: "aggregator",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://api.baiduqianfan.ai/anthropic/tokenplan/team",
    models: ["deepseek-v4-pro"],
    icon: "fluxa",
  },
  {
    key: "volcengine-agent-plan-claude",
    displayName: "火山 Agent Plan",
    appType: "claude",
    family: "volcengine",
    planKey: "agentPlan",
    category: "cn_official",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://ark.cn-beijing.volces.com/api/plan",
    models: ["ark-code-latest"],
    icon: "huoshan",
    iconColor: "#3370FF",
  },
  {
    key: "volcengine-coding-plan-claude",
    displayName: "火山 Coding Plan",
    appType: "claude",
    family: "volcengine",
    planKey: "codingPlan",
    category: "cn_official",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://ark.cn-beijing.volces.com/api/coding",
    models: ["ark-code-latest"],
    icon: "huoshan",
    iconColor: "#3370FF",
  },
  {
    key: "byteplus-claude",
    displayName: "BytePlus",
    appType: "claude",
    category: "cn_official",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://ark.ap-southeast.bytepluses.com/api/coding",
    models: ["ark-code-latest"],
    icon: "byteplus",
    iconColor: "#3370FF",
  },
  {
    key: "siliconflow-en-claude",
    displayName: "SiliconFlow en",
    appType: "claude",
    family: "siliconflow",
    regionKey: "intl",
    category: "aggregator",
    isPartner: true,
    api: "anthropic-messages",
    baseURL: "https://api.siliconflow.com",
    models: ["MiniMaxAI/MiniMax-M3"],
    icon: "siliconflow",
    iconColor: "#000000",
  },
  {
    key: "atlascloud-claude",
    displayName: "AtlasCloud",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://api.atlascloud.ai",
    models: ["zai-org/glm-5.1"],
    icon: "atlascloud",
  },
  {
    key: "soshow-claude",
    displayName: "Soshow",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://maas.so-show.com",
    models: ["claude-sonnet-5"],
    icon: "soshow",
  },
  {
    key: "gemini-native-claude",
    displayName: "Gemini Native",
    appType: "claude",
    category: "third_party",
    api: "anthropic-messages",
    baseURL: "https://generativelanguage.googleapis.com",
    models: ["gemini-3.6-flash"],
    icon: "gemini",
    iconColor: "#4285F4",
  },
  {
    key: "opencode-go-claude",
    displayName: "OpenCode Go",
    appType: "claude",
    family: "opencode",
    planKey: "coding",
    category: "third_party",
    api: "anthropic-messages",
    baseURL: "https://opencode.ai/zen/go",
    models: ["deepseek-v4-flash"],
    icon: "opencode",
    iconColor: "#211E1E",
  },
  {
    key: "opencode-zen-claude",
    displayName: "OpenCode Zen",
    appType: "claude",
    family: "opencode",
    planKey: "payg",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://opencode.ai/zen",
    models: ["claude-sonnet-5-5", "claude-opus-5-5", "claude-haiku-4-5"],
    icon: "opencode",
    iconColor: "#211E1E",
  },
  {
    key: "tencent-token-plan-claude",
    displayName: "Tencent Token Plan",
    appType: "claude",
    family: "tencent",
    planKey: "tokenPlan",
    regionKey: "cn",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.lkeap.cloud.tencent.com/plan/anthropic",
    models: ["tc-code-latest"],
    icon: "tencent",
    iconColor: "#0052D9",
  },
  {
    key: "tencent-token-plan-intl-claude",
    displayName: "Tencent Token Plan (Intl)",
    appType: "claude",
    family: "tencent",
    planKey: "tokenPlan",
    regionKey: "intl",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://tokenhub-intl.tencentcloudmaas.com/plan/anthropic",
    models: ["auto"],
    icon: "tencent",
    iconColor: "#0052D9",
  },
  {
    key: "tencent-token-plan-enterprise-pro-claude",
    displayName: "Tencent Token Plan Enterprise Pro",
    appType: "claude",
    family: "tencent",
    planKey: "enterprisePro",
    regionKey: "cn",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://tokenhub.tencentmaas.com/plan/anthropic",
    models: ["auto"],
    icon: "tencent",
    iconColor: "#0052D9",
  },
  {
    key: "zhipu-glm-en-claude",
    displayName: "Zhipu GLM en",
    appType: "claude",
    family: "zhipu",
    regionKey: "intl",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.z.ai/api/anthropic",
    models: ["glm-5.3"],
    icon: "zhipu",
    iconColor: "#0F62FE",
  },
  {
    key: "baidu-qianfan-coding-plan-claude",
    displayName: "Baidu Qianfan Coding Plan",
    appType: "claude",
    family: "baidu-qianfan",
    planKey: "codingPlan",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://qianfan.baidubce.com/anthropic/coding",
    models: ["qianfan-code-latest"],
    icon: "baidu",
    iconColor: "#2932E1",
  },
  {
    key: "baidu-qianfan-token-plan-claude",
    displayName: "Baidu Qianfan Token Plan",
    appType: "claude",
    family: "baidu-qianfan",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://qianfan.baidubce.com/anthropic/tokenplan/personal",
    models: ["deepseek-v4-pro"],
    icon: "baidu",
    iconColor: "#2932E1",
  },
  {
    key: "qwen-ai-claude",
    displayName: "千问AI平台",
    appType: "claude",
    family: "qianwen",
    planKey: "payg",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://dashscope.aliyuncs.com/apps/anthropic",
    models: ["qwen3.8-max", "qwen3.7-plus", "qwen3.8-flash"],
    icon: "qianwenai",
    iconColor: "#624AFF",
  },
  {
    key: "qwen-ai-token-plan-claude",
    displayName: "千问AI平台 Token Plan",
    appType: "claude",
    family: "qianwen",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://token-plan.cn-beijing.maas.aliyuncs.com/apps/anthropic",
    models: ["qwen3.8-max", "qwen3.7-plus", "qwen3.8-flash"],
    icon: "qianwenai",
    iconColor: "#624AFF",
  },
  {
    key: "qwencloud-claude",
    displayName: "QwenCloud",
    appType: "claude",
    family: "qwencloud",
    planKey: "payg",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://dashscope-intl.aliyuncs.com/apps/anthropic",
    models: ["qwen3.8-max", "qwen3.7-plus", "qwen3.8-flash"],
    icon: "qwencloud",
    iconColor: "#6336E7",
  },
  {
    key: "qwencloud-for-coding-claude",
    displayName: "QwenCloud For Coding",
    appType: "claude",
    family: "qwencloud",
    planKey: "coding",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://coding-intl.dashscope.aliyuncs.com/apps/anthropic",
    models: ["qwen3.7-plus"],
    icon: "qwencloud",
    iconColor: "#6336E7",
  },
  {
    key: "qwencloud-token-plan-claude",
    displayName: "QwenCloud Token Plan",
    appType: "claude",
    family: "qwencloud",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/apps/anthropic",
    models: ["qwen3.8-max", "qwen3.7-plus", "qwen3.8-flash"],
    icon: "qwencloud",
    iconColor: "#6336E7",
  },
  {
    key: "stepfun-en-claude",
    displayName: "StepFun en",
    appType: "claude",
    family: "stepfun",
    regionKey: "intl",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.stepfun.ai/step_plan",
    models: ["step-3.5-flash-2603"],
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  {
    key: "minimax-en-claude",
    displayName: "MiniMax en",
    appType: "claude",
    family: "minimax",
    regionKey: "intl",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://api.minimax.io/anthropic",
    models: ["MiniMax-M3"],
    icon: "minimax",
    iconColor: "#FF6B6B",
  },
  {
    key: "cherryin-claude",
    displayName: "CherryIN",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://open.cherryin.net",
    models: ["anthropic/claude-sonnet-5", "anthropic/claude-opus-5", "anthropic/claude-haiku-4.5"],
    icon: "cherryin",
  },
  {
    key: "therouter-claude",
    displayName: "TheRouter",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://api.therouter.ai",
    models: ["anthropic/claude-sonnet-5", "anthropic/claude-opus-5", "anthropic/claude-haiku-4.5"],
    icon: "therouter",
  },
  {
    key: "novita-ai-claude",
    displayName: "Novita AI",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://api.novita.ai/anthropic",
    models: ["zai-org/glm-5.1"],
    icon: "novita",
    iconColor: "#000000",
  },
  {
    key: "pipellm-claude",
    displayName: "PIPELLM",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://cc-api.pipellm.ai",
    models: ["claude-opus-5", "claude-sonnet-5", "claude-haiku-4-5-20251001"],
    icon: "pipellm",
  },
  {
    key: "xiaomi-mimo-token-plan-china-claude",
    displayName: "Xiaomi MiMo Token Plan (China)",
    appType: "claude",
    family: "xiaomi-mimo",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "anthropic-messages",
    baseURL: "https://token-plan-cn.xiaomimimo.com/anthropic",
    models: ["mimo-v2.6-pro"],
    icon: "xiaomimimo",
    iconColor: "#000000",
  },
  {
    key: "jiekou-ai-claude",
    displayName: "JieKou AI",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://api.jiekou.ai/anthropic",
    models: ["claude-fable-5"],
    icon: "jiekou",
    iconColor: "#000000",
  },
  {
    key: "command-code-claude",
    displayName: "Command Code",
    appType: "claude",
    category: "third_party",
    api: "anthropic-messages",
    baseURL: "https://api.commandcode.ai/provider",
    models: ["deepseek/deepseek-v4.1-flash"],
    icon: "commandcode",
  },
  {
    key: "modelark-claude",
    displayName: "模力方舟",
    appType: "claude",
    category: "aggregator",
    api: "anthropic-messages",
    baseURL: "https://moark.com/anthropic",
    models: ["deepseek-v4-flash-0731"],
    icon: "moark",
  },

  // --- transcribed from CC Switch 4.0.6 (codex, 77 entries) ---
  //
  // Generated from `src/config/codexProviderPresets.ts` by bundling that
  // module and reading the evaluated presets, so these endpoints are the ones
  // CC Switch itself writes rather than the ones its marketing pages suggest.
  // The hand-written block above is kept as-is; anything whose endpoint it
  // already ships is not repeated here.
  //
  // Excluded: entries with no model id (llm-pi-ai rejects an empty model list),
  // OAuth-only entries (DSH has no sign-in path), and endpoint templates like
  // `bedrock-runtime.${AWS_REGION}...` that parse as URLs but cannot be dialled.
  {
    key: "kimi-global-codex",
    displayName: "Kimi Global (Codex)",
    appType: "codex",
    family: "kimi",
    planKey: "payg",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.moonshot.ai/v1",
    models: ["kimi-k3", "kimi-k2.7-code"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "kimi-for-coding-codex",
    displayName: "Kimi For Coding (Codex)",
    appType: "codex",
    family: "kimi",
    planKey: "coding",
    regionKey: "cn",
    category: "cn_official",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.kimi.com/coding/v1",
    models: ["kimi-for-coding", "kimi-for-coding-highspeed", "k3", "k3-256k"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "kimi-for-coding-global-codex",
    displayName: "Kimi For Coding Global (Codex)",
    appType: "codex",
    family: "kimi",
    planKey: "coding",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.kimi.ai/coding/v1",
    models: ["kimi-for-coding", "kimi-for-coding-highspeed", "k3", "k3-256k"],
    icon: "kimi",
    iconColor: "#6366F1",
  },
  {
    key: "zetaapi-codex",
    displayName: "ZetaAPI (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.zetaapi.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "zetaapi",
  },
  {
    key: "apinebula-codex",
    displayName: "APINebula (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://apinebula.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "apinebula",
  },
  {
    key: "aicodemirror-codex",
    displayName: "AICodeMirror (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.aicodemirror.ai/api/codex/backend-api/codex",
    models: ["gpt-5.6-sol"],
    icon: "aicodemirror",
    iconColor: "#000000",
  },
  {
    key: "patewayai-codex",
    displayName: "PatewayAI (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.pateway.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "pateway",
  },
  {
    key: "fennoai-codex",
    displayName: "FennoAI (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.fenno.ai",
    models: ["gpt-5.6-sol"],
    icon: "fenno",
  },
  {
    key: "runapi-codex",
    displayName: "RunAPI (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://runapi.host/v1",
    models: ["gpt-5.6-sol"],
    icon: "runapi",
  },
  {
    key: "shengsuanyun-codex",
    displayName: "Shengsuanyun (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://router.shengsuanyun.com/api/v1",
    models: ["openai/gpt-5.6-sol"],
    icon: "shengsuanyun",
  },
  {
    key: "aigocode-codex",
    displayName: "AIGoCode (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.aigocode.app",
    models: ["gpt-5.6-sol"],
    icon: "aigocode",
    iconColor: "#5B7FFF",
  },
  {
    key: "qiniu-codex",
    displayName: "Qiniu (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.qnaigc.com/bypass/openai/v1",
    models: ["gpt-6-astra"],
    icon: "qiniu",
  },
  {
    key: "aicoding-codex",
    displayName: "AICoding (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.aicoding.inc",
    models: ["gpt-5.6-sol"],
    icon: "aicoding",
    iconColor: "#000000",
  },
  {
    key: "subrouter-codex",
    displayName: "SubRouter (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://subrouter.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "subrouter",
  },
  {
    key: "fluxa-token-plan-codex",
    displayName: "FluxA Token Plan (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.baiduqianfan.ai/v2/tokenplan/team",
    models: ["deepseek-v4-pro", "deepseek-v4-flash-0731", "deepseek-v4-flash", "deepseek-v3.2", "glm-5.2", "glm-5.1", "glm-5", "kimi-k2.6"],
    icon: "fluxa",
  },
  {
    key: "88api-codex",
    displayName: "88API (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.88api.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "88api",
  },
  {
    key: "apikey-fun-codex",
    displayName: "APIKEY.FUN (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.apikey.fan/v1",
    models: ["gpt-5.6-sol"],
    icon: "apikeyfun",
  },
  {
    key: "9527code-codex",
    displayName: "9527CODE (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://9527.codes/v1",
    models: ["gpt-5.6-sol"],
    icon: "9527code",
  },
  {
    key: "code0-codex",
    displayName: "Code0 (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://code0.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "code0",
  },
  {
    key: "teamorouter-codex",
    displayName: "TeamoRouter (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.teamorouter.cn/v1",
    models: ["gpt-5.6-sol"],
    icon: "teamorouter",
  },
  {
    key: "claudecn-codex",
    displayName: "ClaudeCN (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://claudecn.top/v1",
    models: ["gpt-5.6-sol"],
    icon: "claudecn",
  },
  {
    key: "volcengine-agent-plan-codex",
    displayName: "火山 Agent Plan (Codex)",
    appType: "codex",
    family: "volcengine",
    planKey: "agentPlan",
    category: "cn_official",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://ark.cn-beijing.volces.com/api/plan/v3",
    models: ["ark-code-latest"],
    icon: "huoshan",
    iconColor: "#3370FF",
  },
  {
    key: "volcengine-coding-plan-codex",
    displayName: "火山 Coding Plan (Codex)",
    appType: "codex",
    family: "volcengine",
    planKey: "codingPlan",
    category: "cn_official",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://ark.cn-beijing.volces.com/api/coding/v3",
    models: ["ark-code-latest"],
    icon: "huoshan",
    iconColor: "#3370FF",
  },
  {
    key: "byteplus-codex",
    displayName: "BytePlus (Codex)",
    appType: "codex",
    category: "cn_official",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://ark.ap-southeast.bytepluses.com/api/coding/v3",
    models: ["ark-code-latest"],
    icon: "byteplus",
    iconColor: "#3370FF",
  },
  {
    key: "siliconflow-en-codex",
    displayName: "SiliconFlow en (Codex)",
    appType: "codex",
    family: "siliconflow",
    regionKey: "intl",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.siliconflow.com/v1",
    models: ["MiniMaxAI/MiniMax-M3"],
    icon: "siliconflow",
    iconColor: "#000000",
  },
  {
    key: "a6api-codex",
    displayName: "A6API (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.a6api.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "a6api",
  },
  {
    key: "compshare-codex",
    displayName: "Compshare (Codex)",
    appType: "codex",
    family: "compshare",
    planKey: "payg",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.modelverse.cn/v1",
    models: ["gpt-6-astra"],
    icon: "ucloud",
    iconColor: "#000000",
  },
  {
    key: "compshare-coding-plan-codex",
    displayName: "Compshare Coding Plan (Codex)",
    appType: "codex",
    family: "compshare",
    planKey: "codingPlan",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://cp.compshare.cn/v1",
    models: ["gpt-5.6-sol"],
    icon: "ucloud",
    iconColor: "#000000",
  },
  {
    key: "ccsub-codex",
    displayName: "CCSub (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://www.ccsub.net/v1",
    models: ["gpt-6-astra"],
    icon: "ccsub",
  },
  {
    key: "sssaicode-codex",
    displayName: "SSSAiCode (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://node-hk.sssaicodeapi.com/api/v1",
    models: ["gpt-5.6-sol"],
    icon: "sssaicode",
    iconColor: "#000000",
  },
  {
    key: "soleapi-codex",
    displayName: "SoleAPI (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://soleapi.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "soleapi",
  },
  {
    key: "micu-codex",
    displayName: "Micu (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://www.micuapi.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "micu",
    iconColor: "#000000",
  },
  {
    key: "rightcode-codex",
    displayName: "RightCode (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://www.rightapi.ai/codex/v1",
    models: ["gpt-5.6-sol"],
    icon: "rc",
    iconColor: "#E96B2C",
  },
  {
    key: "cubence-codex",
    displayName: "Cubence (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.cubence.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "cubence",
    iconColor: "#000000",
  },
  {
    key: "crazyrouter-codex",
    displayName: "CrazyRouter (Codex)",
    appType: "codex",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://cn.crazyrouter.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "crazyrouter",
    iconColor: "#000000",
  },
  {
    key: "dmxapi-codex",
    displayName: "DMXAPI (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://www.dmxapi.cn/v1",
    models: ["gpt-5.6-sol"],
    icon: "dmxapi",
  },
  {
    key: "sudocode-chat-codex",
    displayName: "SudoCode.chat (Codex)",
    appType: "codex",
    family: "sudocode",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://api.sudocode.chat/v1",
    models: ["gpt-5.6-sol"],
    icon: "sudocode",
  },
  {
    key: "sudocode-us-codex",
    displayName: "SudoCode.us (Codex)",
    appType: "codex",
    family: "sudocode",
    category: "third_party",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://sudocode.us/v1",
    models: ["gpt-5.6-sol"],
    icon: "sudocode-us",
  },
  {
    key: "xycai-codex",
    displayName: "XycAi (Codex)",
    appType: "codex",
    category: "aggregator",
    isPartner: true,
    api: "openai-responses",
    baseURL: "https://apicdn.xycai.us/v1",
    models: ["gpt-5.6-sol"],
    icon: "xycai",
  },
  {
    key: "tu-zi-codex",
    displayName: "Tu-zi (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.tu-zi.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "tuzi",
  },
  {
    key: "amux-codex",
    displayName: "Amux (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.amux.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "amux",
  },
  {
    key: "atlascloud-codex",
    displayName: "AtlasCloud (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.atlascloud.ai/v1",
    models: ["zai-org/glm-5.2"],
    icon: "atlascloud",
  },
  {
    key: "soshow-codex",
    displayName: "Soshow (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://maas.so-show.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "soshow",
  },
  {
    key: "deepseek-codex",
    displayName: "DeepSeek (Codex)",
    appType: "codex",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.deepseek.com",
    models: ["deepseek-flash", "deepseek-v4-pro"],
    icon: "deepseek",
    iconColor: "#1E88E5",
  },
  {
    key: "zhipu-glm-en-codex",
    displayName: "Zhipu GLM en (Codex)",
    appType: "codex",
    family: "zhipu",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.z.ai/api/v1",
    models: ["glm-5.3", "glm-5.3-flash"],
    icon: "zhipu",
    iconColor: "#0F62FE",
  },
  {
    key: "baidu-qianfan-codex",
    displayName: "Baidu Qianfan (Codex)",
    appType: "codex",
    family: "baidu-qianfan",
    planKey: "payg",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://qianfan.baidubce.com/v2",
    models: ["deepseek-v4-pro", "deepseek-v4-flash"],
    icon: "baidu",
    iconColor: "#2932E1",
  },
  {
    key: "baidu-qianfan-coding-plan-codex",
    displayName: "Baidu Qianfan Coding Plan (Codex)",
    appType: "codex",
    family: "baidu-qianfan",
    planKey: "codingPlan",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://qianfan.baidubce.com/v2/coding",
    models: ["qianfan-code-latest"],
    icon: "baidu",
    iconColor: "#2932E1",
  },
  {
    key: "baidu-qianfan-token-plan-codex",
    displayName: "Baidu Qianfan Token Plan (Codex)",
    appType: "codex",
    family: "baidu-qianfan",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://qianfan.baidubce.com/v2/tokenplan/personal",
    models: ["deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4-flash-0731", "glm-5.2", "glm-5.1", "kimi-k2.6"],
    icon: "baidu",
    iconColor: "#2932E1",
  },
  {
    key: "qwen-ai-codex",
    displayName: "千问AI平台 (Codex)",
    appType: "codex",
    family: "qianwen",
    planKey: "payg",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    models: ["qwen3.8-max", "qwen3.8-2.4t-a95b", "qwen3.8-27b"],
    icon: "qianwenai",
    iconColor: "#624AFF",
  },
  {
    key: "qwen-ai-token-plan-codex",
    displayName: "千问AI平台 Token Plan (Codex)",
    appType: "codex",
    family: "qianwen",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    models: ["qwen3.8-max", "qwen3.8-flash"],
    icon: "qianwenai",
    iconColor: "#624AFF",
  },
  {
    key: "qwencloud-codex",
    displayName: "QwenCloud (Codex)",
    appType: "codex",
    family: "qwencloud",
    planKey: "payg",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    models: ["qwen3.8-max", "qwen3.8-flash", "qwen3.7-max", "qwen3.8-2.4t-a95b", "qwen3.8-27b"],
    icon: "qwencloud",
    iconColor: "#6336E7",
  },
  {
    key: "qwencloud-for-coding-codex",
    displayName: "QwenCloud For Coding (Codex)",
    appType: "codex",
    family: "qwencloud",
    planKey: "coding",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://coding-intl.dashscope.aliyuncs.com/v1",
    models: ["qwen3.7-plus", "qwen3.6-plus", "qwen3-coder-plus"],
    icon: "qwencloud",
    iconColor: "#6336E7",
  },
  {
    key: "qwencloud-token-plan-codex",
    displayName: "QwenCloud Token Plan (Codex)",
    appType: "codex",
    family: "qwencloud",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    models: ["qwen3.8-max", "qwen3.8-flash", "qwen3.7-max"],
    icon: "qwencloud",
    iconColor: "#6336E7",
  },
  {
    key: "tencent-hunyuan-codex",
    displayName: "Tencent Hunyuan (Codex)",
    appType: "codex",
    family: "tencent",
    planKey: "payg",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://tokenhub.tencentmaas.com/v1",
    models: ["hy3", "hy4-preview", "hy3-preview"],
    icon: "hunyuan",
    iconColor: "#0055E9",
  },
  {
    key: "tencent-token-plan-codex",
    displayName: "Tencent Token Plan (Codex)",
    appType: "codex",
    family: "tencent",
    planKey: "tokenPlan",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.lkeap.cloud.tencent.com/plan/v3",
    models: ["tc-code-latest", "deepseek-v4-flash-202605", "deepseek-v4-pro-202606", "minimax-m2.7", "glm-5", "glm-5.1", "glm-5.2", "hy3", "hy3-preview"],
    icon: "tencent",
    iconColor: "#0052D9",
  },
  {
    key: "tencent-token-plan-intl-codex",
    displayName: "Tencent Token Plan (Intl) (Codex)",
    appType: "codex",
    family: "tencent",
    planKey: "tokenPlan",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://tokenhub-intl.tencentcloudmaas.com/plan/v3",
    models: ["auto", "glm-5.2", "kimi-k2.6", "deepseek-v4-pro-202606", "deepseek-v4-flash-202605", "minimax-m3"],
    icon: "tencent",
    iconColor: "#0052D9",
  },
  {
    key: "tencent-token-plan-enterprise-pro-codex",
    displayName: "Tencent Token Plan Enterprise Pro (Codex)",
    appType: "codex",
    family: "tencent",
    planKey: "enterprisePro",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://tokenhub.tencentmaas.com/plan/v3",
    models: ["auto", "glm-5.3", "glm-5.2", "glm-5", "glm-5.1", "glm-5-turbo", "kimi-k2.7-code", "kimi-k2.7-code-highspeed", "kimi-k2.6", "minimax-m2.7", "minimax-m3", "deepseek-v4-flash", "deepseek-v4-pro", "deepseek-v4-flash-0731", "deepseek-v4-pro-0813", "deepseek-v4-flash-202605", "deepseek-v4-pro-202606"],
    icon: "tencent",
    iconColor: "#0052D9",
  },
  {
    key: "stepfun-api-codex",
    displayName: "StepFun API (Codex)",
    appType: "codex",
    family: "stepfun",
    planKey: "payg",
    regionKey: "cn",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.stepfun.com/v1",
    models: ["step-3.7-flash"],
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  {
    key: "stepfun-api-en-codex",
    displayName: "StepFun API en (Codex)",
    appType: "codex",
    family: "stepfun",
    planKey: "payg",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.stepfun.ai/v1",
    models: ["step-3.7-flash"],
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  {
    key: "stepfun-en-codex",
    displayName: "StepFun en (Codex)",
    appType: "codex",
    family: "stepfun",
    planKey: "stepPlan",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.stepfun.ai/step_plan/v1",
    models: ["step-3.7-flash", "step-3.5-flash-2603", "step-3.5-flash"],
    icon: "stepfun",
    iconColor: "#16D6D2",
  },
  {
    key: "minimax-en-codex",
    displayName: "MiniMax en (Codex)",
    appType: "codex",
    family: "minimax",
    regionKey: "intl",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://api.minimax.io/v1",
    models: ["MiniMax-M3"],
    icon: "minimax",
    iconColor: "#FF6B6B",
  },
  {
    key: "astron-coding-plan-codex",
    displayName: "Astron Coding Plan (Codex)",
    appType: "codex",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://maas-coding-api.cn-huabei-1.xf-yun.com/v1",
    models: ["astron-code-latest"],
    icon: "astron",
  },
  {
    key: "xiaomi-mimo-token-plan-china-codex",
    displayName: "Xiaomi MiMo Token Plan (China) (Codex)",
    appType: "codex",
    family: "xiaomi-mimo",
    planKey: "tokenPlan",
    category: "cn_official",
    api: "openai-responses",
    baseURL: "https://token-plan-cn.xiaomimimo.com/v1",
    models: ["mimo-v2.6-pro", "mimo-v2.6-flash", "mimo-v2.5-pro", "mimo-v2.5"],
    icon: "xiaomimimo",
    iconColor: "#000000",
  },
  {
    key: "novita-ai-codex",
    displayName: "Novita AI (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.novita.ai/openai/v1",
    models: ["zai-org/glm-5.3"],
    icon: "novita",
    iconColor: "#000000",
  },
  {
    key: "xai-grok-codex",
    displayName: "xAI (Grok) (Codex)",
    appType: "codex",
    category: "third_party",
    api: "openai-responses",
    baseURL: "https://api.x.ai/v1",
    models: ["grok-4.5", "grok-4.7"],
    icon: "xai",
    iconColor: "#000000",
  },
  {
    key: "opencode-go-codex",
    displayName: "OpenCode Go (Codex)",
    appType: "codex",
    family: "opencode",
    planKey: "coding",
    category: "third_party",
    api: "openai-responses",
    baseURL: "https://opencode.ai/zen/go/v1",
    models: ["glm-5.3", "glm-5.3-flash", "kimi-k3", "deepseek-v4-pro", "deepseek-v4-flash", "mimo-v2.5-pro"],
    icon: "opencode",
    iconColor: "#211E1E",
  },
  {
    key: "opencode-zen-codex",
    displayName: "OpenCode Zen (Codex)",
    appType: "codex",
    family: "opencode",
    planKey: "payg",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://opencode.ai/zen/v1",
    models: ["gpt-6-sol"],
    icon: "opencode",
    iconColor: "#211E1E",
  },
  {
    key: "cherryin-codex",
    displayName: "CherryIN (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://open.cherryin.net/v1",
    models: ["openai/gpt-5.6-sol"],
    icon: "cherryin",
  },
  {
    key: "relaxycode-codex",
    displayName: "RelaxyCode (Codex)",
    appType: "codex",
    category: "third_party",
    api: "openai-responses",
    baseURL: "https://www.relaxycode.com/v1",
    models: ["gpt-5.6-sol"],
    icon: "relaxcode",
  },
  {
    key: "e-flowcode-codex",
    displayName: "E-FlowCode (Codex)",
    appType: "codex",
    category: "third_party",
    api: "openai-responses",
    baseURL: "https://e-flowcode.cc/v1",
    models: ["gpt-5.6-sol"],
    icon: "eflowcode",
    iconColor: "#000000",
  },
  {
    key: "pipellm-codex",
    displayName: "PIPELLM (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://cc-api.pipellm.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "pipellm",
  },
  {
    key: "openrouter-codex",
    displayName: "OpenRouter (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://openrouter.ai/api/v1",
    models: ["gpt-5.6-sol"],
    icon: "openrouter",
    iconColor: "#6566F1",
  },
  {
    key: "therouter-codex",
    displayName: "TheRouter (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.therouter.ai/v1",
    models: ["openai/gpt-5.3-codex"],
    icon: "therouter",
  },
  {
    key: "jiekou-ai-codex",
    displayName: "JieKou AI (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.jiekou.ai/openai/v1",
    models: ["claude-fable-5"],
    icon: "jiekou",
    iconColor: "#000000",
  },
  {
    key: "aicodewith-codex",
    displayName: "AICodeWith (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://api.aicodewith.ai/v1",
    models: ["gpt-5.6-sol"],
    icon: "aicodewith",
    iconColor: "#3A3B40",
  },
  {
    key: "command-code-codex",
    displayName: "Command Code (Codex)",
    appType: "codex",
    category: "third_party",
    api: "openai-responses",
    baseURL: "https://api.commandcode.ai/provider/v1",
    models: ["deepseek/deepseek-v4.1-flash", "z-ai/glm-5.3-flash", "Qwen/Qwen3.8-Flash"],
    icon: "commandcode",
  },
  {
    key: "modelark-codex",
    displayName: "模力方舟 (Codex)",
    appType: "codex",
    category: "aggregator",
    api: "openai-responses",
    baseURL: "https://moark.com/v1",
    models: ["deepseek-v4-flash-0731", "DeepSeek-V4-Pro", "GLM-5.3", "Kimi-K2.7-Code", "qwen3-coder-plus"],
    icon: "moark",
  },

])

/**
 * Search aliases, transcribed from CC Switch's `presetSearchAliases.ts`.
 *
 * Keyed by preset key and never displayed: they exist so a search for a
 * vendor's common Chinese or corporate name — 小米 for Xiaomi MiMo, 月之暗面
 * for Kimi, 深度求索 for DeepSeek — finds its entry. The catalogue this port
 * inherited was small enough that their absence went unnoticed; at this size
 * a search that only knows display names is what decides whether the picker
 * is usable at all.
 *
 * Re-keyed from CC Switch, which keys the table by preset *name*. This
 * catalogue suffixes every Codex-side entry with " (Codex)" so one flat list
 * cannot show the same name twice, so a name-keyed lookup would have missed
 * the entire Codex half.
 */
export const PRESET_SEARCH_ALIASES = Object.freeze({
  "baidu-qianfan-coding-plan-claude": "百度 千帆 文心",
  "baidu-qianfan-coding-plan-codex": "百度 千帆 文心",
  "baidu-qianfan-token-plan-claude": "百度 千帆 文心",
  "baidu-qianfan-token-plan-codex": "百度 千帆 文心",
  "bailing-claude": "蚂蚁 百灵 ling",
  "bailing-codex": "蚂蚁 百灵 ling",
  "deepseek-claude": "深度求索",
  "deepseek-codex": "深度求索",
  "gemini-native-claude": "google 谷歌",
  "kimi-claude": "月之暗面 moonshot",
  "kimi-codex": "月之暗面 moonshot",
  "kimi-for-coding-claude": "月之暗面 moonshot",
  "kimi-for-coding-codex": "月之暗面 moonshot",
  "kimi-for-coding-global-claude": "月之暗面 moonshot",
  "kimi-for-coding-global-codex": "月之暗面 moonshot",
  "kimi-global-claude": "月之暗面 moonshot",
  "kimi-global-codex": "月之暗面 moonshot",
  "longcat-claude": "美团",
  "longcat-codex": "美团",
  "minimax-claude": "海螺",
  "minimax-codex": "海螺",
  "minimax-en-claude": "海螺",
  "minimax-en-codex": "海螺",
  "modelscope-claude": "魔搭",
  "modelscope-codex": "魔搭",
  "qwen-ai-claude": "千问 通义 阿里 百炼 bailian aliyun qwen",
  "qwen-ai-codex": "千问 通义 阿里 百炼 bailian aliyun qwen",
  "qwen-ai-token-plan-claude": "千问 通义 阿里 百炼 bailian aliyun qwen",
  "qwen-ai-token-plan-codex": "千问 通义 阿里 百炼 bailian aliyun qwen",
  "qwencloud-claude": "通义 阿里 qwen",
  "qwencloud-codex": "通义 阿里 qwen",
  "qwencloud-for-coding-claude": "通义 阿里 qwen",
  "qwencloud-for-coding-codex": "通义 阿里 qwen",
  "qwencloud-token-plan-claude": "通义 阿里 qwen",
  "qwencloud-token-plan-codex": "通义 阿里 qwen",
  "siliconflow-claude": "硅基流动",
  "siliconflow-codex": "硅基流动",
  "siliconflow-en-claude": "硅基流动",
  "siliconflow-en-codex": "硅基流动",
  "stepfun-claude": "阶跃星辰",
  "stepfun-codex": "阶跃星辰",
  "stepfun-en-claude": "阶跃星辰",
  "stepfun-en-codex": "阶跃星辰",
  "tencent-token-plan-claude": "腾讯 混元 hunyuan",
  "tencent-token-plan-codex": "腾讯 混元 hunyuan",
  "tencent-token-plan-enterprise-pro-claude": "腾讯 混元 hunyuan",
  "tencent-token-plan-enterprise-pro-codex": "腾讯 混元 hunyuan",
  "tencent-token-plan-intl-claude": "腾讯 混元 hunyuan",
  "tencent-token-plan-intl-codex": "腾讯 混元 hunyuan",
  "tu-zi-codex": "兔子 兔子api tuzi",
  "volcengine-agent-plan-claude": "火山 豆包 doubao volcengine 方舟 ark 字节",
  "volcengine-agent-plan-codex": "火山 豆包 doubao volcengine 方舟 ark 字节",
  "volcengine-coding-plan-claude": "火山 豆包 doubao volcengine 方舟 ark 字节",
  "volcengine-coding-plan-codex": "火山 豆包 doubao volcengine 方舟 ark 字节",
  "xai-grok-codex": "grok",
  "xiaomi-mimo-claude": "小米",
  "xiaomi-mimo-codex": "小米",
  "xiaomi-mimo-token-plan-china-claude": "小米",
  "xiaomi-mimo-token-plan-china-codex": "小米",
  "zhipu-glm-claude": "智谱 glm bigmodel z.ai chatglm",
  "zhipu-glm-codex": "智谱 glm bigmodel z.ai chatglm",
  "zhipu-glm-en-claude": "智谱 glm bigmodel z.ai chatglm",
  "zhipu-glm-en-codex": "智谱 glm bigmodel z.ai chatglm",
});

/**
 * The eight categories CC Switch's frontend constrains `category` to.
 *
 * The Rust side types it as a free-form `Option<String>`, so this list is not a
 * validation gate but the vocabulary the picker and the icons are built
 * against — `types.ts` declares exactly these, and `presetGroups.ts` maps them
 * onto the five groups the "add provider" list is sectioned into.
 */
export const CCS_PROVIDER_CATEGORIES = Object.freeze([
  'official',
  'cn_official',
  'cloud_provider',
  'aggregator',
  'third_party',
  'custom',
  'omo',
  'omo-slim',
])

/**
 * The groups the preset picker is sectioned into, transcribed from
 * `presetGroups.ts`'s `PRESET_GROUP_ORDER`: account login, model vendors,
 * third-party platforms, cloud providers, plugin configurations.
 */
export const PRESET_GROUP_ORDER = Object.freeze([
  'login',
  'vendor',
  'thirdparty',
  'cloud',
  'plugin',
])

/**
 * The plans CC Switch's version control can label, transcribed from
 * `presetFamilies.ts`'s `PRESET_PLAN_KEYS`. Exported as the vocabulary a
 * `planKey` is checked against — a value outside it would render as a raw i18n
 * key rather than a label, and `presetVersionLabel` has no fallback for one.
 */
export const PRESET_PLAN_KEYS = Object.freeze([
  'payg',
  'coding',
  'codingPlan',
  'agentPlan',
  'tokenPlan',
  'enterpriseLite',
  'enterprisePro',
  'stepPlan',
  'aksk',
  'apiKey',
])

/** The two regions, in CC Switch's display order (China first). */
export const PRESET_REGION_KEYS = Object.freeze(['cn', 'intl'])

/**
 * Which section a preset belongs to, transcribed from `presetGroups.ts`.
 *
 * CC Switch's own version also sends anything carrying `requiresOAuth` or a
 * `providerType` to `login`. Neither field exists in this catalogue — every
 * entry here authenticates with an API key, because DSH has no OAuth path for a
 * third-party endpoint — so only the category half is reproduced.
 */
export function presetGroup(preset) {
  switch (preset?.category) {
    case 'official':
      return 'login'
    case 'cn_official':
      return 'vendor'
    case 'cloud_provider':
      return 'cloud'
    case 'omo':
    case 'omo-slim':
      return 'plugin'
    default:
      return 'thirdparty'
  }
}

/**
 * The i18n keys for a preset's version suffix, in CC Switch's order: plan
 * first, then region — the two dimensions `presetVersionLabel` joins with "·".
 *
 * Returned as keys rather than a joined string because this module has no
 * translator. A preset declaring neither dimension has no suffix and is shown
 * by its name alone; every such entry here is the only preset for its vendor,
 * so there is no second version to tell it apart from.
 */
export function presetVersionKeys(preset) {
  const keys = []
  if (typeof preset?.planKey === 'string' && preset.planKey !== '') {
    keys.push(`manager.plan.${preset.planKey}`)
  }
  if (typeof preset?.regionKey === 'string' && preset.regionKey !== '') {
    keys.push(`manager.region.${preset.regionKey}`)
  }
  return keys
}

/**
 * The catalogue sectioned for the picker, in `PRESET_GROUP_ORDER`.
 *
 * Empty sections are dropped rather than rendered as a heading with nothing
 * under it. A preset with no category falls to `thirdparty`, which is where
 * CC Switch's own `default` case puts it.
 */
export function groupPresetsByCategory(presets) {
  const list = Array.isArray(presets) ? presets : []
  return PRESET_GROUP_ORDER
    .map((group) => ({ group, presets: list.filter((preset) => presetGroup(preset) === group) }))
    .filter((section) => section.presets.length > 0)
}

/** A preset's key, or undefined when the catalogue has no such entry. */
export function presetByKey(key) {
  return PROVIDER_PRESETS.find((preset) => preset.key === key)
}

/**
 * The provider a preset would create, ready for the save route.
 *
 * `apiKeyEnv` is deliberately absent: the key addresses a credential, and only
 * the save path — which knows whether it is creating or updating — may mint
 * one. A preset that carried a reference could point two providers at one
 * stored secret.
 */
export function providerFromPreset(preset) {
  return {
    displayName: preset.displayName,
    api: preset.api,
    baseURL: preset.baseURL,
    models: preset.models.map((id) => ({ id })),
    appType: preset.appType,
    ...(preset.icon === undefined ? {} : { icon: preset.icon }),
    ...(preset.iconColor === undefined ? {} : { iconColor: preset.iconColor }),
  }
}
/**
 * The host of a preset's endpoint, minus a leading `www.`.
 *
 * Mirrors CC Switch's `presetDomain`. That reads the preset's `websiteUrl`;
 * this catalogue carries no website field, so the endpoint the provider will
 * actually dial is used instead — the same host for every entry that has one,
 * and the one a user is likelier to remember.
 */
export function presetHost(preset) {
  const url = preset?.baseURL;
  if (typeof url !== "string" || url === "") return "";
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

const DOMAIN_PREFIXES = /^(www|api|platform|open|console|cloud|dashboard|app)\./;
const DOMAIN_SUFFIXES =
  /(\.(com|cn|ai|io|net|org|dev|app|top|xyz|cc|co|me|tech|site|pro|vip|us|hk|jp))+$/;

/**
 * A host's body, with the common prefixes and suffixes stripped.
 *
 * Transcribed from CC Switch's `domainBody`. Without it a search for "com" or
 * "api" matches nearly every entry, which is why the host is matched by its
 * body, and only a term that itself contains a dot may match the full host.
 */
export function domainBody(host) {
  return String(host ?? "").replace(DOMAIN_PREFIXES, "").replace(DOMAIN_SUFFIXES, "");
}

/**
 * Whether a preset matches what the user typed.
 *
 * Every whitespace-separated term has to appear somewhere — "zhipu intl" is a
 * narrowing query, not a widening one — and a term containing a dot may match
 * the full host as well as the body.
 *
 * The alias table is what makes this usable at all: someone looking for
 * 月之暗面 or 智谱 will not find "Kimi" or "Zhipu GLM" by name.
 */
export function presetMatches(preset, query) {
  const needle = String(query ?? "").trim().toLowerCase();
  if (needle === "") return true;
  const host = presetHost(preset).toLowerCase();
  const haystack = [preset?.displayName, PRESET_SEARCH_ALIASES[preset?.key], domainBody(host)]
    .filter((value) => typeof value === "string" && value !== "")
    .join(" ")
    .toLowerCase();
  return needle
    .split(/\s+/)
    .every((term) => term.length > 0
      && (haystack.includes(term) || (term.includes(".") && host.includes(term))));
}

